import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :track_conn, TrackConnWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :track_conn, TrackConnWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# The packaged binary is meant to be double-clicked, so open the dashboard in
# the user's browser on launch (see TrackConn.Launcher). Opt out with the
# TRACK_CONN_NO_BROWSER env var.
config :track_conn, :open_browser, true

# Create/upgrade the SQLite schema on boot. A double-clicked binary has no
# chance to run `mix ecto.migrate` first, so the release migrates itself.
config :track_conn, :migrate_on_boot, true

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
